%YAML:1.0
---
thing: "hello world"

ball_red_h_max: 7
ball_red_h_min: 175
ball_red_s_max: 255
ball_red_s_min: 0
ball_red_v_max: 255
ball_red_v_min: 0

ball_green_h_max: 70
ball_green_h_min: 40
ball_green_s_max: 255
ball_green_s_min: 0
ball_green_v_max: 255
ball_green_v_min: 0

pole_yellow_h_max: 100
pole_yellow_h_min: 50
pole_yellow_s_max: 255
pole_yellow_s_min: 0
pole_yellow_v_max: 255
pole_yellow_v_min: 0

stage_index: -1

move_pid_p: 1.2

detect_algorithm: "constraint_limit"
decision_algorithm: "fsm"

width: 640
height: 480

camera_matrix: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 562.546487626155 , 0, 331.020749304873, 0, 560.726740317221, 229.930167086478, 0, 0, 1.0000 ]

distort_matrix: !!opencv-matrix
    rows: 4
    cols: 1
    dt: d
    data: [ -0.0625362260288806,0.0969517251981310, 0.0, 0.0]

fps: 30
